#!/bin/sh
# Automated build script for Youku Html5 Player
# environment: cygwin x64
# /cws: self-written chrome-web-store api tool

if [[ $1 == "" ]]; then
	echo "Missing version param"
	exit
fi
version=$1

path=/cygdrive/D/PHP/Zaddons/youku
files_share="_locales ABPlayer.css ABPlayer.min.js biliplus_shield.min.js CommentCoreLibrary.min.js dom_gen.js flv.min.js google-style-loading.min.js icon.png jquery-2.1.4.min.js md5.js official_html5_enabler.js options.html options.js resizeSensor.js script_executer.js v_slash_jumper.js youku_embed_replacer.js youku_html5.js youku_html5_hack.js"
files_chrome="hookFetch.js hookFetch_background.js"
files_firefox=""
sz="/cygdrive/C/Program Files/7-Zip/7z"
cd "$path"
mkdir -p tmp

amo_token=$(</tmp/amo.token)
amo_key=${amo_token%|*}
amo_secret=${amo_token#*|}

#zip share bundle
"$sz" a build_share.zip $files_share >/dev/null 2>&1

#build chrome
cp build_share.zip build_chrome.zip
sed -e "s/__AutoReplaced_Extension_Version__/${version}/" manifest.json >tmp/manifest.json
"$sz" a build_chrome.zip $files_chrome ./tmp/manifest.json >/dev/null 2>&1
echo "Submitting to CWS"
/cws update fpnknfakcmgkbhccgpgnbaddggjligol build_chrome.zip
/cws publish fpnknfakcmgkbhccgpgnbaddggjligol
curl -o signed.crx -L "https://clients2.google.com/service/update2/crx?response=redirect&prodversion=38.0&x=id%3Dfpnknfakcmgkbhccgpgnbaddggjligol%26installsource%3Dondemand%26uc"

#build firefox
cp build_share.zip build_firefox.zip
sed -e "s/__AutoReplaced_Extension_Version__/${version}/" ff/manifest.json >tmp/manifest.json
echo "Submitting to AMO"
"$sz" x build_firefox.zip -otmp >/dev/null 2>&1
cmd /c web-ext sign --api-key=$amo_key --api-secret=$amo_secret -s tmp -a .
mv -f youku_html5_player-*.xpi signed.xpi

#build firefox listed
echo "Submitting listed version to AMO"
sed -e "s/__AutoReplaced_Extension_Version__/${version}/" ff/store/manifest.json >tmp/manifest.json
cmd /c web-ext sign --api-key=$amo_key --api-secret=$amo_secret -s tmp -a tmp

rm -rf build_share.zip build_chrome.zip build_firefox.zip tmp